log:
  level: info
  disable_sentry: true

listener:
  addr: :8000

db:
  url: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"

core:
  addr: tcp://127.0.0.1:26657

cosmos:
  addr: 127.0.0.1:9090
  enable_tls: false

evm:
  chains:
    - name: "Goerli"
      bridge_address: "0x5A18Bf59748818CF47a1B709b65Dbbd4dA51Ba57"
      submitter_private_key: "2985033f9d4120e351d087b97257ea7eeeec58c729f59f49c3d73c536f0a50bb"
      rpc: https://goerli.infura.io/v3/2a6a01d5162c45939a09d96bea88d358

relay:
  catchup_disabled: true
  issuer_id: [ '', '' ]
  disable_filtration: true